Map<String, dynamic> danceMoves = {
  "Apple Jacks": 9,
  "Around the World Charleston": null,
  "Ball Change": null,
  "Baggy Pants/Cool Breeze in the Knees": null,
  "Bees Knees": null,
  "Black Bottom": 48,
  "Boogie Back (aka 'Back it up')": 71,
  "Boogie Drops": null,
  "Boogie Forward": 89,
  "Boogie Forward (clap behind)": 95,
  "Boogie Step": 102,
  "Box Step": 112,
  "Break (Half break) (aka 'Tiger Rag break')": 212,
  "Break (Shim Sham) (aka 'TOBA break')": 160,
  "Break-a-leg": 237,
  "Camel Walks": 260,
  "Chase": null,
  "Cartwheel": 322,
  "Charleston (1920s)": 339,
  "Charleston (Jump)": 353,
  "Charleston (Kansas City)": 365,
  "Crazy Legs": 427,
  "Cross step": 460,
  "Crossovers": 449,
  "Dust your Apron": null,
  "Duck Walks": null,
  "Eagle Slide": 482,
  "Fall off the Log": 524,
  "Fishtails": 541,
  "Gaze Afar": 549,
  "Glide (Travelling Step)": null,
  "Grinds": 556,
  "Groove Walks": null,
  "Hallelujahs (aka 'Shouts')": 584,
  "Half Break": null,
  "Heels (Digs)": 618,
  "Heels (Russian wing)": 628,
  "Helicopter": null,
  "Hitch Hike": null,
  "Hitch Hiking": null,
  "Hitchhiker": 642,
  "Itches": 663,
  "Jig Walks": 669,
  "Jump Charleston": null,
  "Kick Ball Change": null,
  "Knee Slaps": 689,
  "Lockstep": 695,
  "Lowdown": 704,
  "Mess Around": 738,
  "Mooch (aka 'Four Corners')": 747,
  "Opposites (aka 'Push n Pull')": 771,
  "Paddle Turn": 793,
  "Paddle Wheel": null,
  "Pecks": 803,
  "Pecks (Jackson 5)": 847,
  "Pimp Walk": null,
  "Ride the Pony": 871,
  "Rocks": 886,
  "Rubber Legs": null,
  "Rusty Dusty": 905,
  "Sailor Kicks": 919,
  "Savoy Kicks": 935,
  "Scarecrow": 965,
  "Scissor Kicks": 971,
  "Scissor Step/Kicks": null,
  "Scuff Step": null,
  "Shim Sham": 981,
  "Shim Sham Break": null,
  "Shoe Shine": 1031,
  "Shish-ka-boom-ba": 1021,
  "Shorty George": 1035,
  "Skate": 1043,
  "Skip Up": 1051,
  "Slip Slops": 1058,
  "Snake Hips": null,
  "Spank the Baby": 1063,
  "Squat Charleston": 378,
  "Step Touch": null,
  "Step Steps": null,
  "Stomp off": 1068,
  "Struttin'": 1074,
  "Suzie Q": 1087,
  "Tabby the Cat": 1097,
  "Tacky Annie": 1145,
  "Tick Tocks": 1155,
  "Trucking": 1163,
  "Triple Steps": null,
  "Turkey Trots": 1176,
  "Twists": null,
};
