List<String> movesList = [
  "Apple Jacks",
  "Around the World Charleston",
  "Ball Change",
  "Baggy Pants/Cool Breeze in the Knees",
  "Bees Knees",
  "Black Bottom",
  "Boogie Back (aka 'Back it up')",
  "Boogie Drops",
  "Boogie Forward",
  "Boogie Forward (clap behind)",
  "Boogie Step",
  "Box Step",
  "Break (Half break) (aka 'Tiger Rag break')",
  "Break (Shim Sham) (aka 'TOBA break')",
  "Break-a-leg",
  "Camel Walks",
  "Chase",
  "Cartwheel",
  "Charleston (1920s)",
  "Charleston (Jump)",
  "Charleston (Kansas City)",
  "Crazy Legs",
  "Cross step",
  "Crossovers",
  "Dust your Apron",
  "Duck Walks",
  "Eagle Slide",
  "Fall off the Log",
  "Fall off the Log (turning)",
  "Fishtails",
  "Fishtail",
  "Gaze Afar",
  "Glide (Travelling Step)",
  "Grinds",
  "Hallelujahs (aka 'Shouts')",
  "Half Break",
  "Heels (Digs)",
  "Heels (Russian wing)",
  "Helicopter",
  "Hitch Hike",
  "Hitch Hiking",
  "Hitchhiker",
  "Itches",
  "Jig Walks",
  "Jump Charleston",
  "Kick Ball Change",
  "Knee Slaps",
  "Lockstep",
  "Lowdown",
  "Mess Around",
  "Mooch (aka 'Four Corners')",
  "Opposites (aka 'Push n Pull')",
  "Paddle Turn",
  "Paddle Wheel",
  "Pecking",
  "Pecks",
  "Pecks (Jackson 5)",
  "Pimp Walk",
  "Ride the Pony",
  "Rocks",
  "Rubber Legs",
  "Rusty Dusty",
  "Sailor Kicks",
  "Savoy Kicks",
  "Scarecrow",
  "Scissor Kicks",
  "Scissor Step/Kicks",
  "Scuff Step",
  "Shim Sham",
  "Shim Sham Break",
  "Shine your Shoes",
  "Shish-ka-boom-ba",
  "Shorty George",
  "Skate",
  "Skates",
  "Skip Up",
  "Slip Slop",
  "Slip Slops",
  "Snake Hips",
  "Spank the Baby",
  "Squat Charleston",
  "Step Touch",
  "Stomp off",
  "Struttin'",
  "Suzie Q",
  "Tabby the Cat",
  "Tacky Annie",
  "Tick Tocks",
  "Trucking",
  "Triple Steps",
  "Turkey Trots",
  "Twists",
  "Groove Walks",
  "Step Steps"
];
